"""Code Dojo exercises: real Python, checked by real tests in the sandbox."""
from __future__ import annotations


def T(name, expr, expected=None, tol=1e-6, setup=None):
    t = {"name": name, "expr": expr, "tol": tol}
    if expected is not None:
        t["expected"] = expected
    if setup:
        t["setup"] = setup
    return t


EXERCISES = [
    dict(id="ex_variables", title="Your First Variables", concept="py_variables", tier=1,
         prompt="Create a variable `hours` equal to 7 and a variable `rate` equal to 2.5. Then create `total` equal to hours multiplied by rate.",
         starter="hours = \nrate = \ntotal = \nprint(total)",
         tests=[T("hours is 7", "hours", 7), T("rate is 2.5", "rate", 2.5), T("total = hours * rate", "total", 17.5)],
         hints=["Assignment uses a single `=`: `hours = 7`.", "Multiply with `*`."], solution="hours = 7\nrate = 2.5\ntotal = hours * rate\nprint(total)"),
    dict(id="ex_conditions", title="Grade Machine", concept="py_conditions", tier=1,
         prompt="Write `grade(score)` that returns 'A' if score >= 90, 'B' if score >= 70, otherwise 'C'.",
         starter="def grade(score):\n    # your code here\n    pass",
         tests=[T("grade(95)", "grade(95)", "A"), T("grade(90) (boundary)", "grade(90)", "A"), T("grade(75)", "grade(75)", "B"), T("grade(12)", "grade(12)", "C")],
         hints=["Use if / elif / else.", "Check the highest threshold first."], solution="def grade(score):\n    if score >= 90:\n        return 'A'\n    elif score >= 70:\n        return 'B'\n    return 'C'"),
    dict(id="ex_loops", title="Sum the Evens", concept="py_loops", tier=1,
         prompt="Write `total_even(nums)` that returns the sum of the even numbers in the list.",
         starter="def total_even(nums):\n    total = 0\n    # loop over nums here\n    return total",
         tests=[T("[1,2,3,4]", "total_even([1,2,3,4])", 6), T("empty list", "total_even([])", 0), T("negatives", "total_even([-2, 5, 8])", 6)],
         hints=["`n % 2 == 0` is True for even numbers."], solution="def total_even(nums):\n    total = 0\n    for n in nums:\n        if n % 2 == 0:\n            total += n\n    return total"),
    dict(id="ex_mean", title="Write mean()", concept="py_functions", tier=1,
         prompt="Write `mean(values)` returning the average of a list of numbers. Return 0.0 for an empty list (avoid dividing by zero!).",
         starter="def mean(values):\n    pass",
         tests=[T("mean([2,4,9])", "mean([2,4,9])", 5.0), T("single value", "mean([7])", 7.0), T("empty list", "mean([])", 0.0)],
         hints=["sum(values) / len(values)", "Check `if not values:` first."], solution="def mean(values):\n    if not values:\n        return 0.0\n    return sum(values) / len(values)"),
    dict(id="ex_dicts", title="Count the Labels", concept="py_dicts", tier=1,
         prompt="Write `count_labels(labels)` that returns a dict mapping each label to how many times it appears. This is how you check class balance!",
         starter="def count_labels(labels):\n    counts = {}\n    return counts",
         tests=[T("spam/ham", "count_labels(['spam','ham','ham'])", {"spam": 1, "ham": 2}), T("empty", "count_labels([])", {})],
         hints=["counts[label] = counts.get(label, 0) + 1"], solution="def count_labels(labels):\n    counts = {}\n    for l in labels:\n        counts[l] = counts.get(l, 0) + 1\n    return counts"),
    dict(id="ex_numpy", title="Standardise with NumPy", concept="numpy_basics", tier=2,
         prompt="Write `standardize(x)` that takes a NumPy array and returns (x - mean) / std — without a Python loop. `numpy` is available as `np`.",
         setup="import numpy as np",
         starter="import numpy as np\n\ndef standardize(x):\n    x = np.asarray(x, dtype=float)\n    pass",
         tests=[T("mean ≈ 0", "abs(standardize([1,2,3,4,5]).mean())", 0.0, 1e-9), T("std ≈ 1", "standardize([1,2,3,4,5]).std()", 1.0),
                T("values", "list(standardize([10, 20, 30]).round(4))", [-1.2247, 0.0, 1.2247], 1e-4)],
         hints=["x.mean() and x.std() work on whole arrays.", "Return (x - x.mean()) / x.std()"], solution="import numpy as np\n\ndef standardize(x):\n    x = np.asarray(x, dtype=float)\n    return (x - x.mean()) / x.std()"),
    dict(id="ex_pandas", title="Filter a DataFrame", concept="pandas_basics", tier=2,
         prompt="Write `pass_rate(df)` that returns the fraction of students who passed (passed == 1) among those with study_hours > 5.",
         setup="import pandas as pd\ndf_test = pd.DataFrame({'study_hours':[1,6,8,10,3], 'passed':[0,1,0,1,1]})",
         starter="import pandas as pd\n\ndef pass_rate(df):\n    pass",
         tests=[T("example DataFrame", "pass_rate(df_test)", 2 / 3), T("all pass", "pass_rate(pd.DataFrame({'study_hours':[6,7],'passed':[1,1]}))", 1.0)],
         hints=["Filter: df[df['study_hours'] > 5]", "The mean of a 0/1 column is the fraction of 1s."], solution="def pass_rate(df):\n    sub = df[df['study_hours'] > 5]\n    return sub['passed'].mean()"),
    dict(id="ex_accuracy", title="Implement Accuracy", concept="accuracy", tier=2,
         prompt="Write `accuracy(y_true, y_pred)` returning the fraction of matching positions.",
         starter="def accuracy(y_true, y_pred):\n    pass",
         tests=[T("3 of 4", "accuracy([1,0,1,1],[1,0,0,1])", 0.75), T("perfect", "accuracy([0,0],[0,0])", 1.0)],
         hints=["zip(y_true, y_pred) pairs them up."], solution="def accuracy(y_true, y_pred):\n    return sum(t == p for t, p in zip(y_true, y_pred)) / len(y_true)"),
    dict(id="ex_confusion", title="Build a Confusion Matrix", concept="confusion_matrix", tier=2,
         prompt="Write `confusion(y_true, y_pred)` for binary labels 0/1, returning [[TN, FP], [FN, TP]].",
         starter="def confusion(y_true, y_pred):\n    tn = fp = fn = tp = 0\n    return [[tn, fp], [fn, tp]]",
         tests=[T("example", "confusion([1,0,1,1,0,0],[1,1,0,1,0,0])", [[2, 1], [1, 2]]), T("all correct", "confusion([0,1],[0,1])", [[1, 0], [0, 1]])],
         hints=["Loop over pairs and increment the right counter.", "FP = predicted 1, actually 0."], solution="def confusion(y_true, y_pred):\n    tn = fp = fn = tp = 0\n    for t, p in zip(y_true, y_pred):\n        if t == 1 and p == 1: tp += 1\n        elif t == 0 and p == 1: fp += 1\n        elif t == 1 and p == 0: fn += 1\n        else: tn += 1\n    return [[tn, fp], [fn, tp]]"),
    dict(id="ex_precision_recall", title="Precision & Recall", concept="recall", tier=3,
         prompt="Write `precision_recall(y_true, y_pred)` returning a tuple (precision, recall) for positive class 1. If a denominator is zero, use 0.0.",
         starter="def precision_recall(y_true, y_pred):\n    pass",
         tests=[T("example", "precision_recall([1,0,1,1,0],[1,1,0,1,0])", [2 / 3, 2 / 3]), T("no positives predicted", "precision_recall([1,0],[0,0])", [0.0, 0.0]),
                T("lazy fraud model", "precision_recall([0]*98+[1]*2, [0]*100)", [0.0, 0.0])],
         hints=["precision = TP/(TP+FP); recall = TP/(TP+FN)", "Guard: `tp / (tp + fp) if (tp + fp) else 0.0`"],
         solution="def precision_recall(y_true, y_pred):\n    tp = sum(t == 1 and p == 1 for t, p in zip(y_true, y_pred))\n    fp = sum(t == 0 and p == 1 for t, p in zip(y_true, y_pred))\n    fn = sum(t == 1 and p == 0 for t, p in zip(y_true, y_pred))\n    prec = tp / (tp + fp) if tp + fp else 0.0\n    rec = tp / (tp + fn) if tp + fn else 0.0\n    return prec, rec"),
    dict(id="ex_mse", title="MSE and RMSE", concept="rmse", tier=2,
         prompt="Write `mse(y, yhat)` and `rmse(y, yhat)`.",
         starter="import math\n\ndef mse(y, yhat):\n    pass\n\ndef rmse(y, yhat):\n    pass",
         tests=[T("mse", "mse([1,2,3],[1,2,5])", 4 / 3), T("rmse", "rmse([0,0],[3,4])", (12.5) ** 0.5)],
         hints=["Average of squared differences.", "rmse = math.sqrt(mse(...))"], solution="import math\n\ndef mse(y, yhat):\n    return sum((a - b) ** 2 for a, b in zip(y, yhat)) / len(y)\n\ndef rmse(y, yhat):\n    return math.sqrt(mse(y, yhat))"),
    dict(id="ex_split", title="Shuffle & Split", concept="train_test_split", tier=3,
         prompt="Write `split(n, test_ratio, seed)` returning (train_idx, test_idx): lists of indices 0..n-1, shuffled with `random.Random(seed)`, test size = round(n * test_ratio). No index may appear in both!",
         starter="import random\n\ndef split(n, test_ratio, seed):\n    pass",
         tests=[T("sizes", "[len(x) for x in split(10, 0.2, 0)]", [8, 2]), T("disjoint", "len(set(split(50,0.3,1)[0]) & set(split(50,0.3,1)[1]))", 0),
                T("covers everything", "sorted(split(20,0.25,3)[0] + split(20,0.25,3)[1])", list(range(20))),
                T("reproducible with same seed", "split(30,0.2,7) == split(30,0.2,7)")],
         hints=["idx = list(range(n)); random.Random(seed).shuffle(idx)", "k = round(n * test_ratio); test = idx[:k]"],
         solution="import random\n\ndef split(n, test_ratio, seed):\n    idx = list(range(n))\n    random.Random(seed).shuffle(idx)\n    k = round(n * test_ratio)\n    return idx[k:], idx[:k]"),
    dict(id="ex_neuron", title="A Neuron in NumPy", concept="neuron", tier=3,
         prompt="Write `sigmoid(z)` (works on arrays) and `neuron(x, w, b)` returning sigmoid(w·x + b).",
         setup="import numpy as np",
         starter="import numpy as np\n\ndef sigmoid(z):\n    pass\n\ndef neuron(x, w, b):\n    pass",
         tests=[T("sigmoid(0)", "float(sigmoid(0))", 0.5), T("vectorised", "list(np.round(sigmoid(np.array([-100., 0., 100.])), 3))", [0.0, 0.5, 1.0], 1e-3),
                T("neuron", "float(neuron([1, 2], [0.5, -0.25], 0.1))", 1 / (1 + 2.718281828459045 ** -0.1), 1e-6)],
         hints=["1 / (1 + np.exp(-z))", "np.dot(w, x) + b"], solution="import numpy as np\n\ndef sigmoid(z):\n    return 1 / (1 + np.exp(-np.asarray(z, dtype=float)))\n\ndef neuron(x, w, b):\n    return sigmoid(np.dot(w, x) + b)"),
    dict(id="ex_gd", title="Gradient Descent by Hand", concept="gradient_descent", tier=3,
         prompt="Loss L(w) = (w - 3)². Its gradient is 2(w - 3). Write `minimize(w0, lr, steps)` that runs gradient descent and returns the final w.",
         starter="def minimize(w0, lr, steps):\n    w = w0\n    for _ in range(steps):\n        grad = None  # compute the gradient\n        # update w\n    return w",
         tests=[T("converges to 3", "minimize(0.0, 0.1, 200)", 3.0, 1e-4), T("one step", "minimize(0.0, 0.1, 1)", 0.6), T("too-large lr diverges", "abs(minimize(0.0, 1.5, 20)) > 1000")],
         hints=["grad = 2 * (w - 3)", "w = w - lr * grad"], solution="def minimize(w0, lr, steps):\n    w = w0\n    for _ in range(steps):\n        grad = 2 * (w - 3)\n        w = w - lr * grad\n    return w"),
    dict(id="ex_knn", title="k-NN from Scratch", concept="knn", tier=4,
         prompt="Write `knn_predict(X_train, y_train, x, k)` → majority label among the k nearest training points (Euclidean distance). Ties: any of the tied labels is fine.",
         setup="import numpy as np",
         starter="import numpy as np\nfrom collections import Counter\n\ndef knn_predict(X_train, y_train, x, k):\n    pass",
         tests=[T("nearest is class 1", "knn_predict([[0,0],[5,5],[6,5]], [0,1,1], [5.5,5], 1)", 1),
                T("vote of 3", "knn_predict([[0,0],[0,1],[5,5]], [0,0,1], [1,1], 3)", 0),
                T("works with numpy arrays", "knn_predict(np.array([[1.,1.],[9.,9.]]), np.array([3, 7]), np.array([8.,8.]), 1)", 7)],
         hints=["d = np.linalg.norm(np.asarray(X_train) - np.asarray(x), axis=1)", "idx = np.argsort(d)[:k]; Counter(labels).most_common(1)"],
         solution="import numpy as np\nfrom collections import Counter\n\ndef knn_predict(X_train, y_train, x, k):\n    d = np.linalg.norm(np.asarray(X_train, float) - np.asarray(x, float), axis=1)\n    idx = np.argsort(d)[:k]\n    return Counter(np.asarray(y_train)[idx].tolist()).most_common(1)[0][0]"),
    dict(id="ex_sklearn", title="Train a Real Classifier", concept="logistic_regression", tier=4,
         prompt="`X` and `y` are provided (500 samples). Split 80/20 with random_state=0 and stratify=y, train a LogisticRegression, and store the test accuracy in a variable named `test_acc`. Target: ≥ 0.80.",
         setup="from sklearn.datasets import make_classification\nX, y = make_classification(n_samples=500, n_features=6, n_informative=4, random_state=1)",
         starter="from sklearn.model_selection import train_test_split\nfrom sklearn.linear_model import LogisticRegression\n\n# X, y already exist\n\ntest_acc = None\nprint(test_acc)",
         tests=[T("test_acc is a number", "isinstance(test_acc, float)"), T("test_acc ≥ 0.80", "test_acc >= 0.80")],
         hints=["X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=0, stratify=y)", "model.score(X_test, y_test) returns accuracy"],
         solution="from sklearn.model_selection import train_test_split\nfrom sklearn.linear_model import LogisticRegression\n\nX_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=0, stratify=y)\nmodel = LogisticRegression(max_iter=1000).fit(X_train, y_train)\ntest_acc = float(model.score(X_test, y_test))\nprint(test_acc)"),
    dict(id="ex_cosine", title="Vector Search", concept="vector_search", tier=4,
         prompt="Write `cosine(a, b)` and `top_k(query, vectors, k)` returning the indices of the k most similar vectors (highest cosine first).",
         setup="import numpy as np",
         starter="import numpy as np\n\ndef cosine(a, b):\n    pass\n\ndef top_k(query, vectors, k):\n    pass",
         tests=[T("orthogonal", "float(cosine([1,0],[0,1]))", 0.0), T("same direction", "float(cosine([1,1],[3,3]))", 1.0),
                T("top-2", "list(top_k([1,0], [[0,1],[1,0.1],[-1,0],[0.9,0.5]], 2))", [1, 3])],
         hints=["np.dot(a,b) / (np.linalg.norm(a) * np.linalg.norm(b))", "np.argsort(-scores)[:k]"],
         solution="import numpy as np\n\ndef cosine(a, b):\n    a, b = np.asarray(a, float), np.asarray(b, float)\n    return float(a @ b / (np.linalg.norm(a) * np.linalg.norm(b)))\n\ndef top_k(query, vectors, k):\n    scores = np.array([cosine(query, v) for v in vectors])\n    return [int(i) for i in np.argsort(-scores)[:k]]"),
    dict(id="ex_chunk", title="Chunk a Document", concept="chunking", tier=4,
         prompt="Write `chunk_words(text, size, overlap)` that splits text into chunks of `size` words where consecutive chunks share `overlap` words. The last chunk may be shorter; stop once the end of the text is included.",
         starter="def chunk_words(text, size, overlap):\n    words = text.split()\n    chunks = []\n    return chunks",
         tests=[T("no overlap", "chunk_words('a b c d e f', 2, 0)", ["a b", "c d", "e f"]), T("overlap 1", "chunk_words('a b c d e', 3, 1)", ["a b c", "c d e"]),
                T("short text", "chunk_words('hello world', 10, 2)", ["hello world"])],
         hints=["step = size - overlap", "Loop i from 0 in steps; break when i + size >= len(words)."],
         solution="def chunk_words(text, size, overlap):\n    words = text.split()\n    chunks, i, step = [], 0, size - overlap\n    while True:\n        chunks.append(' '.join(words[i:i + size]))\n        if i + size >= len(words):\n            break\n        i += step\n    return chunks"),
    dict(id="ex_guardrail", title="Tool Gateway", concept="permissions", tier=5,
         prompt="Write `allow_tool(tool, task_tools, source, approved)` for an agent gateway. Rules: (1) tools not in `task_tools` are denied; (2) any call whose `source` is 'data' (came from retrieved text) is denied; (3) 'send_email' and 'delete_file' additionally require approved == True. Return True/False.",
         starter="SENSITIVE = {'send_email', 'delete_file'}\n\ndef allow_tool(tool, task_tools, source, approved):\n    pass",
         tests=[T("read tool from user", "allow_tool('search_docs', {'search_docs'}, 'user', False)", True),
                T("tool not enabled", "allow_tool('send_email', {'search_docs'}, 'user', True)", False),
                T("instruction from data", "allow_tool('send_email', {'send_email'}, 'data', True)", False),
                T("sensitive without approval", "allow_tool('delete_file', {'delete_file'}, 'user', False)", False),
                T("sensitive with approval", "allow_tool('delete_file', {'delete_file'}, 'user', True)", True)],
         hints=["Check the rules in order and return False early."],
         solution="SENSITIVE = {'send_email', 'delete_file'}\n\ndef allow_tool(tool, task_tools, source, approved):\n    if tool not in task_tools:\n        return False\n    if source == 'data':\n        return False\n    if tool in SENSITIVE and not approved:\n        return False\n    return True"),
]

BY_ID = {e["id"]: e for e in EXERCISES}


def public(ex: dict, reveal_solution: bool = False) -> dict:
    d = {k: v for k, v in ex.items() if k not in ("solution", "tests", "setup")}
    d["tests"] = [{"name": t["name"]} for t in ex["tests"]]
    if reveal_solution:
        d["solution"] = ex["solution"]
    return d
